### PR TITLE
Override the `ami`

### PR DESCRIPTION
**Pull request by nitrocode**
## what
* Override the `ami`

## why
* Sometimes you want to ensure that your plan is the same and it's difficult to do if the ami is different. By allowing the module to override the ami, I can pin it down and only show the plan relevant to my other changes.

## references
N/A

### CODE REVIEW

**Review by osterman — DISMISSED** [review]

**Comment by nitrocode** [comment]
Don't merge until the sg module refactor and merge.

**Review by Gowiem — APPROVED** [review]

**Pull request merged**
