### PR TITLE
Fix typo in the description of instance_type var

### PR DESCRIPTION
**Pull request by alexandrusavin**
## what
- Fix typo in the description of `instance_type` var

## why
- Avoids confusion

### CODE REVIEW

**Review by joe-niland — DISMISSED** [review]

**Comment by joe-niland** [comment]
@alexandrusavin please have a look at test output.
I think Terraform outputs need updating.

**Comment by alexandrusavin** [comment]
> @alexandrusavin please have a look at test output.
> I think Terraform outputs need updating.

Ups... I've updated the branch before checking the test output so I lost it. I don't know if the tests are scheduled automatically or you need to do it so I can see the output again.

**Comment by joe-niland** [comment]
@alexandrusavin they are run using chat commands but are restricted to contributors

**Comment by alexandrusavin** [comment]
@joe-niland I'm a bit confused by the test output. There were though some missed descriptions that needed update. I added 2 more commits. Is this what the tests caught?

**Comment by alexandrusavin** [comment]
This is the output of the 2 failing tests:
```shell
not ok 8 check if terraform providers are properly pinned
# (in test file test/.test-harness/test/terraform/provider-pinning.bats, line 30)
#   `grep -Eo '^\".*\|[^\~]*\"$' $TMPFILE | diff $TMPFILE -' failed
# --- /tmp/terraform-providers-2XiQMk7nRCM.txt
# +++ -
# @@ -1,3 +0,0 @@
# -"aws|~> 2.55"
# -"null|~> 2.1"
# -"template|~> 2.1"
not ok 9 check if terraform providers have explicit source locations for TF =>0.13
# (in test file test/.test-harness/test/terraform/provider-pinning.bats, line 41)
#   `grep -Ev '^\".*\|null"$' $TMPFILE | diff $TMPFILE -' failed
# --- /tmp/terraform-providers-x7ZvsE14FiX.txt
# +++ -
# @@ -1,3 +0,0 @@
# -"aws|null"
# -"null|null"
# -"template|null"
```

**Comment by joe-niland** [comment]
@alexandrusavin there is currently an issue with one or two of the tests sowe have to hold off until fixed. I will try again now though to see what happens.

**Review by joe-niland — APPROVED** [review]

**Pull request merged**
