### PR TITLE
Add instance_profile variable, Add user_data_base64 variable

### PR DESCRIPTION
**Pull request by htplbc**
## what
* Add instance_profile variable
* Add user_data_base64 variable

## why
* Need the ability to override the module's instance_profile
* Allows the use of cloud_init based configurations

### CODE REVIEW

**Review by osterman — DISMISSED** [review]

**Comment by joe-niland** [comment]
@osterman @htplbc just a thought on the ECR permissions. Some of the AWS API actions require repository name/ID so should this module tighten the permissions to target specific repository/ies? Or is it acceptable to be broad here?

**Comment by osterman** [comment]
@htplbc seems like we are overstepping here to @joe-niland point. Maybe this should be parameterized or not the responsibility of the module.

**Comment by joe-niland** [comment]
FWIW, I have often used the role output in the consuming module to add specific policies where it doesn't make sense for the module to manage certain IAM access.

That said, I don't understand the use case here.

**Comment by htplbc** [comment]
> FWIW, I have often used the role output in the consuming module to add specific policies where it doesn't make sense for the module to manage certain IAM access.
> 
> That said, I don't understand the use case here.

I've added an `instance_profile` to overwrite the current one if needed

**Review by osterman — APPROVED** [review]

**Pull request merged**
