### PR TITLE
fix: ec2 instance constant termination/creation if ebs enabled

### PR DESCRIPTION
**Pull request by www44**
## what

Fix AWS instance idempotency if an EBS volume is configured.

## why

- To prevent AWS ec2 instance termination by each terraform run, even if no changes exist.

## references

- https://github.com/hashicorp/terraform-provider-aws/issues/20305

### CODE REVIEW

**Comment by nitrocode** [comment]
Please rebuild the docs and push up

**Review by nitrocode — APPROVED** [review]

**Comment by goruha** [comment]
@nitrocode fixed

**Review by nitrocode — APPROVED** [review]

**Comment by nitrocode** [comment]
@goruha thanks. it might be better to exclude the examples dir from the tflint check. I had to do the same fix in another repo so it's possible that more repos may be affected.

I also approved but it's still requires codeowner approval from cloudposse/admins. Could you review this PR?

**Review by goruha — APPROVED** [review]

**Review by gberenice — APPROVED** [review]

**Review by milldr — APPROVED** [review]

**Pull request merged**
